version: "3.8"

services:
  backend:
    image: spring-backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://host.docker.internal:5432/Collegemanagement
      DB_USERNAME: postgres
      DB_PASSWORD: 2530
    restart: unless-stopped
