version: "3.8"

services:
  backend:
    image: spring-backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://ep-red-waterfall-ahgls7ur-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_o8nOWb4sXPim
    restart: unless-stopped
